apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [auth.anonymous]
    enabled = true
    org_name = "Main Org."
    org_role = Viewer
    [auth.basic]
    enabled = true
